# Generated by Django 6.1 on 2026-08-22 18:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_reset_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerprofile',
            name='id_document',
            field=models.FileField(blank=True, null=True, upload_to='verification/'),
        ),
        migrations.AddField(
            model_name='providerprofile',
            name='id_document_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='providerprofile',
            name='verification_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='providerprofile',
            name='verification_status',
            field=models.CharField(choices=[('UNVERIFIED', 'Unverified'), ('PENDING', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='UNVERIFIED', max_length=20),
        ),
        migrations.CreateModel(
            name='PushToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255, unique=True)),
                ('platform', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Push Token',
                'verbose_name_plural': 'Push Tokens',
            },
        ),
    ]
