# Generated by Django 6.1 on 2026-08-22 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_providerprofile_id_document_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerprofile',
            name='account_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='providerprofile',
            name='account_number_last4',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='providerprofile',
            name='bank_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='providerprofile',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='providerprofile',
            name='payout_ready',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='providerprofile',
            name='recipient_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
